function Select_size_data(v)
[sizes_filename, sizes_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
    if isequal(sizes_filename,0), return; end;
    commands.setNodeSizes(v, [sizes_pathname sizes_filename]);
% end Select_size_data
