function Select_size_data(v)
[sizes_filename, sizes_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
    if isequal(sizes_filename,0), return; end;
    [value_sizes, ~]=xlsread([sizes_pathname sizes_filename]);
    v.value_sizes=value_sizes;       
    guidata(v.hMainFigure,v)
% end Select_size_data