function Select_matrix_data(v)
[matrix_filename, matrix_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
    if isequal(matrix_filename,0), return; end;
    [matrix, ~]=xlsread([matrix_pathname matrix_filename]);
    v.matrix=matrix;     
    guidata(v.hMainFigure,v)
