function SelectFileToOpen(v)
    [list_filename, list_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
    if isequal(list_filename,0), return; end;
    
    [~, list_regions]=xlsread([list_pathname list_filename]);
    v.list_regions=list_regions;
    guidata(v.hMainFigure,v)
