% --- Add matrix
function Add_matrix_Callback(obj, ~)
v=guidata(obj);

[matrix_filename, matrix_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
if isequal(matrix_filename,0), return; end;
commands.addMatrix(v, [matrix_pathname matrix_filename]);
