% Callback functions
% --- add a circle with default options
function Add_nodes_Callback(obj, ~)
[list_filename, list_pathname] = uigetfile( ...
                    {'*.xlsx;', 'excel files (*.xlsx)';...
                    '*.xls;', 'excel files (*.xls)'; ...
                    '*.*',       'All Files (*.*)'},...
                    'Select a text file');
if isequal(list_filename,0), return; end;
commands.addCircle(guidata(obj), [list_pathname list_filename]);
